-- ==========================================
/* Borrar Objetos creados */
-- ==========================================
DROP TABLE [INTEGRADIGEX].[dbo].ANTO_INVENTARIO;
DROP SEQUENCE ANTO_INVENTARIO_SEQ;
DROP TABLE [INTEGRADIGEX].[dbo].[ANTO_DETALLE_VENTA];
DROP TABLE [INTEGRADIGEX].[dbo].[ANTO_VENTA];
DROP SEQUENCE ANTO_VENTA_SEQ;
DROP TABLE [INTEGRADIGEX].[dbo].ANTO_PRODUCTO;
DROP SEQUENCE ANTO_PRODUCTO_SEQ;
DROP TABLE [INTEGRADIGEX].[dbo].[ANTO_CLIENTE]
DROP SEQUENCE ANTO_CLIENTE_SEQ;

--SELECT NEXT VALUE FOR CONS_PRODUCTO_SEQ; 
--default NEXT VALUE FOR ANTO_CLIENTE_SEQ
--default NEXT VALUE FOR ANTO_INVENTARIO_SEQ
--SELECT NEXT VALUE FOR ANTO_VENTA_SEQ; 

-- ==========================================
/* Creando tabla [ANTO_PRODUCTO] */
-- ==========================================

CREATE SEQUENCE ANTO_PRODUCTO_SEQ
    AS int  
    START WITH 1  
    INCREMENT BY 1  
    MINVALUE 1
	MAXVALUE  2147483647
	 NO CYCLE ;

CREATE TABLE [INTEGRADIGEX].[dbo].ANTO_PRODUCTO
(
	CONS_PRODUCTO int not null default NEXT VALUE FOR ANTO_PRODUCTO_SEQ,
	NOMBRE varchar(100) not null,
	DESCRIPCION varchar(300),
	VALOR_UNIDAD money not null default 0,
	ESTADO int not null default 1, -- Activo=1, Inactivo=2
	FECHA_REGISTRO date not null default GETDATE()
);

ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_PRODUCTO
   ADD CONSTRAINT ANTO_PRODUCTO_PK PRIMARY KEY CLUSTERED (CONS_PRODUCTO);

-- ==========================================
/* Creando tabla [ANTO_INVENTARIO] */
-- ==========================================

CREATE SEQUENCE ANTO_INVENTARIO_SEQ
    AS int  
    START WITH 1  
    INCREMENT BY 1  
    MINVALUE 1
	MAXVALUE  2147483647
    NO CYCLE;


CREATE TABLE [INTEGRADIGEX].[dbo].ANTO_INVENTARIO
(
	CONS_INVENTARIO int not null default NEXT VALUE FOR ANTO_INVENTARIO_SEQ,
	CONS_PRODUCTO int not null,
	STOCK int not null default 0,
	ESTADO int not null default 1,-- Activo=1, Inactivo=2
	FECHA_REGISTRO date not null default GETDATE()
);

ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_INVENTARIO
   ADD CONSTRAINT ANTO_INVENTARIO_PK PRIMARY KEY CLUSTERED (CONS_INVENTARIO);

ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_INVENTARIO
   ADD CONSTRAINT ANTO_INVENTARIO_FK_01 FOREIGN KEY (CONS_PRODUCTO) REFERENCES [INTEGRADIGEX].[dbo].ANTO_PRODUCTO (CONS_PRODUCTO);


-- ==========================================
/* Creando tabla [ANTO_CLIENTE] */
-- ==========================================
CREATE SEQUENCE ANTO_CLIENTE_SEQ
    AS int  
    START WITH 1  
    INCREMENT BY 1  
    MINVALUE 1
	MAXVALUE  2147483647
	 NO CYCLE;
	
CREATE TABLE [INTEGRADIGEX].[dbo].[ANTO_CLIENTE]
(
	CONS_CLIENTE int not null default NEXT VALUE FOR ANTO_CLIENTE_SEQ,
	TIPO_IDENTIFICACION int not null,
	NUMERO_IDENTIFICACION int not null,
	PRIMER_NOMBRE varchar(50) not null,
	SEGUNDO_NOMBRE varchar(50),
	PRIMER_APELLIDO varchar(50) not null,
	SEGUNDO_APELLIDO varchar(50),
	EMAIL varchar(50) not null,
	DIRECCION_RESIDENCIAL varchar(100),
	DIRECCION_TRABAJO varchar(100),
	TELEFONO_CELULAR varchar(50),
	TELEFONO_FIJO varchar(50),
	ESTADO int not null default 1,-- Activo=1, Inactivo=2
	FECHA_REGISTRO date not null default GETDATE()
);

ALTER TABLE  [INTEGRADIGEX].[dbo].[ANTO_CLIENTE]
   ADD CONSTRAINT ANTO_CLIENTE_PK PRIMARY KEY CLUSTERED (CONS_CLIENTE);

   CREATE UNIQUE INDEX ANTO_CLIENTE_IDX_01 ON  [INTEGRADIGEX].[dbo].[ANTO_CLIENTE] (TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION);
   
   
-- ==========================================
/* Creando tabla [ANTO_VENTA] */
-- ==========================================

CREATE SEQUENCE ANTO_VENTA_SEQ
    AS int  
    START WITH 1  
    INCREMENT BY 1  
    MINVALUE 1
	MAXVALUE  2147483647
    NO CYCLE;

CREATE TABLE [INTEGRADIGEX].[dbo].ANTO_VENTA
(
	CONS_VENTA int not null default NEXT VALUE FOR ANTO_VENTA_SEQ,
	CONS_CLIENTE int not null,
	ESTADO int not null default 3,-- En Proceso=3, Procesada=4
	FECHA_REGISTRO date not null default GETDATE()
);

ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_VENTA
   ADD CONSTRAINT ANTO_VENTA_PK PRIMARY KEY CLUSTERED (CONS_VENTA);

ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_VENTA
   ADD CONSTRAINT ANTO_VENTA_FK_01 FOREIGN KEY (CONS_CLIENTE) REFERENCES [INTEGRADIGEX].[dbo].ANTO_CLIENTE (CONS_CLIENTE);
   	  
	-- ==========================================
/* Creando tabla [ANTO_DETALLE_VENTA] */
-- ==========================================

CREATE TABLE [INTEGRADIGEX].[dbo].ANTO_DETALLE_VENTA
(
	CONS_VENTA int not null,
	CONS_PRODUCTO int not null,
	CANTIDAD int not null,
	VALOR_UNITARIO int not null,
	IVA int not null,
	ESTADO int not null default 3,-- En Proceso=3, Procesada=4
	FECHA_REGISTRO date not null default GETDATE()
);

ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_DETALLE_VENTA
   ADD CONSTRAINT ANTO_DETALLE_VENTA_PK PRIMARY KEY CLUSTERED (CONS_VENTA,CONS_PRODUCTO);

ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_DETALLE_VENTA
   ADD CONSTRAINT ANTO_DETALLE_VENTA_FK_01 FOREIGN KEY (CONS_VENTA) REFERENCES [INTEGRADIGEX].[dbo].ANTO_VENTA (CONS_VENTA);
   	  
ALTER TABLE  [INTEGRADIGEX].[dbo].ANTO_DETALLE_VENTA
   ADD CONSTRAINT ANTO_DETALLE_VENTA_FK_02 FOREIGN KEY (CONS_PRODUCTO) REFERENCES [INTEGRADIGEX].[dbo].ANTO_PRODUCTO (CONS_PRODUCTO);

